In [1]:
import numpy as np

# 1. Create Arrays

a=np.array([1,2,3])
b=np.zeros((3,2))
c=np.ones((2,3))
d=np.full((2,3),7)
e=np.arange(10)
f=np.linspace(1,2,5) # (end-start)/(intervals-1)

a,b,c,d,e,f

(array([1, 2, 3]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1.  , 1.25, 1.5 , 1.75, 2.  ]))

In [2]:
# Simulate 10 distance readings from a robot sensor

sensor_readings=np.linspace(2.0,3.0,10)
sensor_readings

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [3]:
# Random operations
import numpy as np

i=np.random.uniform(0,1,(3,2))
a=np.random.randint(1,10,(2,3))
c=np.random.rand(1,3)
a,i,c

(array([[9, 8, 2],
        [8, 6, 9]], dtype=int32),
 array([[0.39316246, 0.04226461],
        [0.22303907, 0.15756538],
        [0.77904046, 0.27359782]]),
 array([[0.76680968, 0.78426823, 0.35829752]]))

In [4]:
sensor_readings=np.linspace(2.0,3.0,10)
sensor_readings

# ADD NOISE (still NumPy)
noise=np.random.uniform(-0.1,0.1,10)
noisy_readings=sensor_readings+noise
noisy_readings

array([1.99650376, 2.11636861, 2.12227839, 2.3951644 , 2.45972847,
       2.59242789, 2.67628507, 2.71739729, 2.97240816, 2.93279167])

In [5]:
a=noisy_readings.mean()    # used in sensor fusion
b=noisy_readings.max()     # used for obstacle detection
c=noisy_readings.min()     # used for obstacle detection
a,b,c

(np.float64(2.4981353713479555),
 np.float64(2.9724081603303567),
 np.float64(1.996503763202568))